name:                matrix-sdk
version:             0.0.1.0
description:         See the README.md file
github:              "livmackintosh/matrix-sdk-haskell"
license:             AGPL-3.0
author:              "Olivia Mackintosh"
maintainer:          "livvy@base.nu"
copyright:           "Copyright © 2020 Olivia Mackintosh"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cryptonite
- memory
- optparse-applicative
- req
- text
- transformers
- unordered-containers

library:
  source-dirs: src

executables:
  matrix-bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-sdk
    extra-libraries: olm

tests:
  matrix-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-sdk
