name:                matrix-sdk
version:             0.0.1.0
description:         See the README.md file
github:              "livmackintosh/matrix-sdk-haskell"
license:             AGPL-3
author:              "Olivia Mackintosh"
maintainer:          "livvy@base.nu"
copyright:           "Copyright © 2020 Olivia Mackintosh"
category:            "API"
synopsis:            SDK for the [matrix] protocol

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base                 >= 4.7     && < 5
- aeson                >= 1.5.1   && < 1.6
- bytestring           >= 0.10.10 && < 0.11
- cryptonite           >= 0.26    && < 0.27
- memory               >= 0.15.0  && < 0.16
- MonadRandom          >= 0.5.1   && < 0.6
- optparse-applicative >= 0.15.1  && < 0.16
- req                  >= 3.2.0   && < 3.3
- text                 >= 1.2.3   && < 1.3
- transformers         >= 0.5.6   && < 0.6
- unordered-containers >= 0.2.10  && < 0.3


library:
  source-dirs: src

executables:
  matrix-bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-sdk
    extra-libraries: olm

tests:
  matrix-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-sdk
